<a href="https://colab.research.google.com/github/MiitaliGupta/MachineLearning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn


## Importing the dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv('/content/drive/MyDrive/6th Sem/Machine Learning/Social_Network_Ads - Social_Network_Ads.csv')
X = dataset.iloc[:, [1, 2, 3]].values
y = dataset.iloc[:, -1].values


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

**`Encode character values`**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
print(X_train)

[[1 26 15000]
 [1 60 102000]
 [0 38 112000]
 [1 40 107000]
 [0 42 53000]
 [1 35 59000]
 [1 48 41000]
 [0 48 134000]
 [0 38 113000]
 [1 29 148000]
 [0 26 15000]
 [1 60 42000]
 [1 24 19000]
 [1 42 149000]
 [0 46 96000]
 [1 28 59000]
 [1 39 96000]
 [1 28 89000]
 [1 41 72000]
 [1 45 26000]
 [0 33 69000]
 [0 20 82000]
 [1 31 74000]
 [1 42 80000]
 [0 35 72000]
 [0 33 149000]
 [1 40 71000]
 [0 51 146000]
 [1 46 79000]
 [1 35 75000]
 [1 38 51000]
 [0 36 75000]
 [0 37 78000]
 [1 38 61000]
 [0 60 108000]
 [0 20 82000]
 [1 57 74000]
 [1 42 65000]
 [1 26 80000]
 [1 46 117000]
 [1 35 61000]
 [0 21 68000]
 [0 28 44000]
 [1 41 87000]
 [0 37 33000]
 [1 27 90000]
 [1 39 42000]
 [1 28 123000]
 [0 31 118000]
 [1 25 87000]
 [0 35 71000]
 [1 37 70000]
 [1 35 39000]
 [1 47 23000]
 [0 35 147000]
 [0 48 138000]
 [1 26 86000]
 [1 25 79000]
 [0 52 138000]
 [1 51 23000]
 [0 35 60000]
 [0 33 113000]
 [1 30 107000]
 [1 48 33000]
 [0 41 80000]
 [0 48 96000]
 [1 31 18000]
 [0 31 71000]
 [1 43 129000]
 [0 59 76000]
 

In [ ]:
print(y_train)

[0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1
 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1
 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1
 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0
 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0
 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1
 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0]


In [ ]:
print(X_test)

[[1 30 87000]
 [0 38 50000]
 [1 35 75000]
 [0 30 79000]
 [0 35 50000]
 [1 27 20000]
 [0 31 15000]
 [1 36 144000]
 [0 18 68000]
 [1 47 43000]
 [1 30 49000]
 [0 28 55000]
 [1 37 55000]
 [1 39 77000]
 [1 20 86000]
 [0 32 117000]
 [1 37 77000]
 [1 19 85000]
 [0 55 130000]
 [1 35 22000]
 [0 35 47000]
 [0 47 144000]
 [0 41 51000]
 [1 47 105000]
 [0 23 28000]
 [0 49 141000]
 [0 28 87000]
 [1 29 80000]
 [0 37 62000]
 [0 32 86000]
 [1 21 88000]
 [1 37 79000]
 [1 57 60000]
 [1 37 53000]
 [1 24 58000]
 [1 18 52000]
 [1 22 81000]
 [0 34 43000]
 [0 31 34000]
 [0 49 36000]
 [1 27 88000]
 [1 41 52000]
 [0 27 84000]
 [1 35 20000]
 [0 43 112000]
 [0 27 58000]
 [0 37 80000]
 [0 52 90000]
 [1 26 30000]
 [1 49 86000]
 [0 57 122000]
 [0 34 25000]
 [0 35 57000]
 [1 34 115000]
 [0 59 88000]
 [1 45 32000]
 [0 29 83000]
 [0 26 80000]
 [1 49 28000]
 [1 23 20000]
 [1 32 18000]
 [1 60 42000]
 [1 19 76000]
 [1 36 99000]
 [0 19 26000]
 [1 60 83000]
 [0 24 89000]
 [1 27 58000]
 [1 40 47000]
 [0 42 70000]
 [0 32 1500

In [ ]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0
 0 1 1 1 0 1 0 0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.99288247 -1.1631724  -1.5849703 ]
 [ 0.99288247  2.17018137  0.93098672]
 [-1.00716855  0.0133054   1.22017719]
 [ 0.99288247  0.20938504  1.07558195]
 [-1.00716855  0.40546467 -0.48604654]
 [ 0.99288247 -0.28081405 -0.31253226]
 [ 0.99288247  0.99370357 -0.8330751 ]
 [-1.00716855  0.99370357  1.8563962 ]
 [-1.00716855  0.0133054   1.24909623]
 [ 0.99288247 -0.86905295  2.26126285]
 [-1.00716855 -1.1631724  -1.5849703 ]
 [ 0.99288247  2.17018137 -0.80415605]
 [ 0.99288247 -1.35925203 -1.46929411]
 [ 0.99288247  0.40546467  2.2901819 ]
 [-1.00716855  0.79762394  0.75747245]
 [ 0.99288247 -0.96709276 -0.31253226]
 [ 0.99288247  0.11134522  0.75747245]
 [ 0.99288247 -0.96709276  0.55503912]
 [ 0.99288247  0.30742485  0.06341534]
 [ 0.99288247  0.69958412 -1.26686079]
 [-1.00716855 -0.47689368 -0.0233418 ]
 [-1.00716855 -1.7514113   0.3526058 ]
 [ 0.99288247 -0.67297331  0.12125343]
 [ 0.99288247  0.40546467  0.29476771]
 [-1.00716855 -0.28081405  0.06341534]
 [-1.00716855 -0.47689368

In [ ]:
print(X_test)

[[ 0.99288247 -0.77101313  0.49720103]
 [-1.00716855  0.0133054  -0.57280368]
 [ 0.99288247 -0.28081405  0.15017248]
 [-1.00716855 -0.77101313  0.26584866]
 [-1.00716855 -0.28081405 -0.57280368]
 [ 0.99288247 -1.06513258 -1.44037507]
 [-1.00716855 -0.67297331 -1.5849703 ]
 [ 0.99288247 -0.18277423  2.14558666]
 [-1.00716855 -1.94749093 -0.05226085]
 [ 0.99288247  0.89566375 -0.775237  ]
 [ 0.99288247 -0.77101313 -0.60172273]
 [-1.00716855 -0.96709276 -0.42820845]
 [ 0.99288247 -0.08473441 -0.42820845]
 [ 0.99288247  0.11134522  0.20801057]
 [ 0.99288247 -1.7514113   0.46828198]
 [-1.00716855 -0.5749335   1.36477242]
 [ 0.99288247 -0.08473441  0.20801057]
 [ 0.99288247 -1.84945111  0.43936294]
 [-1.00716855  1.67998229  1.74072002]
 [ 0.99288247 -0.28081405 -1.38253697]
 [-1.00716855 -0.28081405 -0.65956082]
 [-1.00716855  0.89566375  2.14558666]
 [-1.00716855  0.30742485 -0.54388463]
 [ 0.99288247  0.89566375  1.01774386]
 [-1.00716855 -1.45729185 -1.2090227 ]
 [-1.00716855  1.09174339

## Training the K-NN model on the Training set

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train) 

KNeighborsClassifier()

**# Predict output for the test set and compare with the existing Y value**

In [ ]:
y_pred = classifier.predict(X_test)
print (y_pred)
print (y_test)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 0
 0 0 1 1 1 1 0 0 1]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0
 0 1 1 1 0 1 0 0 1]


**#Accuracy and Confusion Matrix values**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm=confusion_matrix(y_test,y_pred)
print (cm)

ac = accuracy_score(y_test,y_pred)
print (ac)

[[73  6]
 [ 4 37]]
0.9166666666666666


## Predicting a new result

In [ ]:
print(classifier.predict(sc.transform([[1,30,870000]])))

[1]


## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[73  6]
 [ 4 37]]


0.9166666666666666